### ISSUE TITLE
Cant do anything(i suppose i might dont know)

### ISSUE THREAD

**Issue by rahulgupta9817** [Krish-Depani/Decentralized-Voting-System-Using-Ethereum-Blockchain#1]
I have done everything as in the steps perfectly. everything was fine but..
<img width="952" alt="image" src="https://github.com/Krish-Depani/Decentralized-Voting-System/assets/167807377/eddb4885-ba92-439f-a47b-a73bcfb0592c">
as you can see created the data base and all. Apparently when  i try to login using that credential i have created i cant login while from above seeing those requests i eventually figured out that it not recognized my data base(MYSQL) server address that i wrote in .env file. So please help me i really dont know what to write in the field of MYSQL_DB.  even wrote http://localhost:8000 0r with different ports and also 12.0.0.1 . everything this how currently it looks like: MYSQL_USER="admin"
MYSQL_PASSWORD="BlockChain1234"
MYSQL_HOST="DESKTOP-FUGQNF4"
MYSQL_DB="voter_db"
SECRET_KEY="d2b861a623b1d0e89f7c91c313bce1db34fbce8356ca80cf38b72e4c5a832ed5f0fa7136ef0ed5c32641308daa88c29c108d85835afcf37e5385c8e2c4cacee6"  Please help me fix this

**Comment by KushalGowdaa** [comment]
> I have done everything as in the steps perfectly. everything was fine but..
> <img width="952" alt="image" src="https://github.com/Krish-Depani/Decentralized-Voting-System/assets/167807377/eddb4885-ba92-439f-a47b-a73bcfb0592c">
> as you can see created the data base and all. Apparently when  i try to login using that credential i have created i cant login while from above seeing those requests i eventually figured out that it not recognized my data base(MYSQL) server address that i wrote in .env file. So please help me i really dont know what to write in the field of MYSQL_DB.  even wrote http://localhost:8000 0r with different ports and also 12.0.0.1 . everything this how currently it looks like: MYSQL_USER="admin"
> MYSQL_PASSWORD="BlockChain1234"
> MYSQL_HOST="DESKTOP-FUGQNF4"
> MYSQL_DB="voter_db"
> SECRET_KEY="d2b861a623b1d0e89f7c91c313bce1db34fbce8356ca80cf38b72e4c5a832ed5f0fa7136ef0ed5c32641308daa88c29c108d85835afcf37e5385c8e2c4cacee6"  Please help me fix this

Hey try typing "localhost" in the field of MYSQL_HOST.

**Comment by Tharun-Techie** [comment]
> > I have done everything as in the steps perfectly. everything was fine but..
> > <img alt="image" width="952" src="https://private-user-images.githubusercontent.com/167807377/324568240-eddb4885-ba92-439f-a47b-a73bcfb0592c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMjI2ODMsIm5iZiI6MTcyMDEyMjM4MywicGF0aCI6Ii8xNjc4MDczNzcvMzI0NTY4MjQwLWVkZGI0ODg1LWJhOTItNDM5Zi1hNDdiLWE3M2JjZmIwNTkyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQxOTQ2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTA2NzUwNDU2NTE3OGQ0ZTUxNjBkMjJjODcyMTViODdmZTg2YmJkYTdhNDY3ODg2YmFmNWU2MGU5OTg2MjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BqfO8-XM9iakIb1LLKzB3tikroq7uvt5MZhMpNklpXA">
> > as you can see created the data base and all. Apparently when  i try to login using that credential i have created i cant login while from above seeing those requests i eventually figured out that it not recognized my data base(MYSQL) server address that i wrote in .env file. So please help me i really dont know what to write in the field of MYSQL_DB.  even wrote http://localhost:8000 0r with different ports and also 12.0.0.1 . everything this how currently it looks like: MYSQL_USER="admin"
> > MYSQL_PASSWORD="BlockChain1234"
> > MYSQL_HOST="DESKTOP-FUGQNF4"
> > MYSQL_DB="voter_db"
> > SECRET_KEY="d2b861a623b1d0e89f7c91c313bce1db34fbce8356ca80cf38b72e4c5a832ed5f0fa7136ef0ed5c32641308daa88c29c108d85835afcf37e5385c8e2c4cacee6"  Please help me fix this
> 
> Hey try typing "localhost" in the field of MYSQL_HOST.

hello bro i have the same issue MYSQL_USER="root@localhost"
MYSQL_PASSWORD="root"
MYSQL_HOST="localhost"
MYSQL_DB="voter_db"
SECRET_KEY="d2b861a623b1d0e89f7c91c313bce1db34fbce8356ca80cf38b72e4c5a832ed5f0fa7136ef0ed5c32641308daa88c29c108d85835afcf37e5385c8e2c4cacee6" so i changed as u said but still not cleared yet

**Comment by Tharun-Techie** [comment]
> > > I have done everything as in the steps perfectly. everything was fine but..
> > > <img alt="image" width="952" src="https://private-user-images.githubusercontent.com/167807377/324568240-eddb4885-ba92-439f-a47b-a73bcfb0592c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMjI2ODMsIm5iZiI6MTcyMDEyMjM4MywicGF0aCI6Ii8xNjc4MDczNzcvMzI0NTY4MjQwLWVkZGI0ODg1LWJhOTItNDM5Zi1hNDdiLWE3M2JjZmIwNTkyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQxOTQ2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTA2NzUwNDU2NTE3OGQ0ZTUxNjBkMjJjODcyMTViODdmZTg2YmJkYTdhNDY3ODg2YmFmNWU2MGU5OTg2MjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BqfO8-XM9iakIb1LLKzB3tikroq7uvt5MZhMpNklpXA">
> > > as you can see created the data base and all. Apparently when  i try to login using that credential i have created i cant login while from above seeing those requests i eventually figured out that it not recognized my data base(MYSQL) server address that i wrote in .env file. So please help me i really dont know what to write in the field of MYSQL_DB.  even wrote http://localhost:8000 0r with different ports and also 12.0.0.1 . everything this how currently it looks like: MYSQL_USER="admin"
> > > MYSQL_PASSWORD="BlockChain1234"
> > > MYSQL_HOST="DESKTOP-FUGQNF4"
> > > MYSQL_DB="voter_db"
> > > SECRET_KEY="d2b861a623b1d0e89f7c91c313bce1db34fbce8356ca80cf38b72e4c5a832ed5f0fa7136ef0ed5c32641308daa88c29c108d85835afcf37e5385c8e2c4cacee6"  Please help me fix this
> > 
> > 
> > Hey try typing "localhost" in the field of MYSQL_HOST.
> 
> hello bro i have the same issue MYSQL_USER="root@localhost" MYSQL_PASSWORD="root" MYSQL_HOST="localhost" MYSQL_DB="voter_db" SECRET_KEY="d2b861a623b1d0e89f7c91c313bce1db34fbce8356ca80cf38b72e4c5a832ed5f0fa7136ef0ed5c32641308daa88c29c108d85835afcf37e5385c8e2c4cacee6" so i changed as u said but still not cleared yet

![image](https://github.com/Krish-Depani/Decentralized-Voting-System/assets/93753661/d70bf3ce-19f9-4037-a01a-c3a27a6f83ea)

**Comment by KushalGowdaa** [comment]
> > > I have done everything as in the steps perfectly. everything was fine but..
> > > <img alt="image" width="952" src="https://private-user-images.githubusercontent.com/167807377/324568240-eddb4885-ba92-439f-a47b-a73bcfb0592c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMjI2ODMsIm5iZiI6MTcyMDEyMjM4MywicGF0aCI6Ii8xNjc4MDczNzcvMzI0NTY4MjQwLWVkZGI0ODg1LWJhOTItNDM5Zi1hNDdiLWE3M2JjZmIwNTkyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwNFQxOTQ2MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTA2NzUwNDU2NTE3OGQ0ZTUxNjBkMjJjODcyMTViODdmZTg2YmJkYTdhNDY3ODg2YmFmNWU2MGU5OTg2MjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BqfO8-XM9iakIb1LLKzB3tikroq7uvt5MZhMpNklpXA">
> > > as you can see created the data base and all. Apparently when  i try to login using that credential i have created i cant login while from above seeing those requests i eventually figured out that it not recognized my data base(MYSQL) server address that i wrote in .env file. So please help me i really dont know what to write in the field of MYSQL_DB.  even wrote http://localhost:8000 0r with different ports and also 12.0.0.1 . everything this how currently it looks like: MYSQL_USER="admin"
> > > MYSQL_PASSWORD="BlockChain1234"
> > > MYSQL_HOST="DESKTOP-FUGQNF4"
> > > MYSQL_DB="voter_db"
> > > SECRET_KEY="d2b861a623b1d0e89f7c91c313bce1db34fbce8356ca80cf38b72e4c5a832ed5f0fa7136ef0ed5c32641308daa88c29c108d85835afcf37e5385c8e2c4cacee6"  Please help me fix this
> > 
> > Hey try typing "localhost" in the field of MYSQL_HOST.
> 
> hello bro i have the same issue MYSQL_USER="root@localhost"
> MYSQL_PASSWORD="root"
> MYSQL_HOST="localhost"
> MYSQL_DB="voter_db"
> SECRET_KEY="d2b861a623b1d0e89f7c91c313bce1db34fbce8356ca80cf38b72e4c5a832ed5f0fa7136ef0ed5c32641308daa88c29c108d85835afcf37e5385c8e2c4cacee6" so i changed as u said but still not cleared yet
> 

Hey why is the MySQL user given as root@localhost I think it should be the user name that you've given while setting up the MySQL db check that out 

Even if the problem continues check the port where the MySQL db is running and specify the port if it is other than 3306

**Comment by KushalGowdaa** [comment]
did it work?

**Comment by rahulgupta9817** [comment]
Bro thanks for replying
I summit that project. Thanks

**Comment by rahulgupta9817** [comment]
The 401 error is because of
Not giving environmental permission for SQL workbench.

Mention this in your readme file

**Comment by c-m2003** [comment]
![Screenshot 2024-09-15 230544](https://github.com/user-attachments/assets/fe30c8da-5cd9-47fc-8108-c66e947160d6)
can someone tell me the reason for the error in the console

**Comment by KushalGowdaa** [comment]
Is Ganache running in the background??

**Comment by c-m2003** [comment]
yes

**Comment by c-m2003** [comment]
> Is Ganache running in the background??

yes

**Comment by KushalGowdaa** [comment]
> > Is Ganache running in the background??
> 
> yes
> 
Did you try resolving the issue using the steps given in the below link 
https://stackoverflow.com/questions/48694192/contract-has-not-been-deployed-to-detected-network-network-artifact-mismatch-o

**Comment by ghost** [comment]
getting npm command not found error in vs code how to solve it

**Comment by KushalGowdaa** [comment]
> getting npm command not found error in vs code how to solve it
> 

Have you installed nodeJs on your pc if not go to nodeJs's website and then install the nodejs prebuilt installer for windows or any platform you're using and then try the npm commands

**Comment by Rahulreddy2004** [comment]
Can you pls Guide me how to create database and how to link
